
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { BrainCircuit, Cpu, LayoutDashboard, LineChart, MessageCircle, PlayCircle, Server, ShieldCheck, Sparkles, Wallet } from "lucide-react";
import Link from "next/link";

const demoSteps = [
    {
        icon: <LayoutDashboard className="w-8 h-8 text-primary" />,
        title: "1. The Dashboard: Your Financial Command Center",
        description: "Start here. This is your high-level overview, designed to give you an instant snapshot of your financial health.",
        points: [
            {
                icon: <Wallet className="w-5 h-5 text-primary" />,
                title: "Key Metrics & Net Worth",
                text: "Instantly see your assets, liabilities, and net worth. The 'Net Worth Over Time' chart visualizes your financial journey, making trends easy to spot."
            },
            {
                icon: <Sparkles className="w-5 h-5 text-emerald-500" />,
                title: "The AI Financial Summary (Key Feature!)",
                text: "This isn't just static text. Explain that this summary is generated by a Genkit Agent. When it creates the summary, it sees you have stocks and actively uses the 'getStockPrice' tool to fetch live market data. This makes the summary dynamic and far more accurate."
            }
        ]
    },
    {
        icon: <MessageCircle className="w-8 h-8 text-primary" />,
        title: "2. The Chat Assistant: Your Financial Agent",
        description: "This is where you can have a direct conversation with your finances. Click the bot icon in the bottom right.",
        points: [
            {
                icon: <Cpu className="w-5 h-5 text-primary" />,
                title: "Ask Simple & Complex Questions",
                text: "Start with a simple query like 'How much is my car loan?'. Then, ask something complex: 'Can I afford to buy a new laptop for ₹1,00,000?'. Explain that behind the scenes, a Genkit Flow is taking your question and your financial data, sending it to Gemini for a personalized answer."
            },
            {
                icon: <BrainCircuit className="w-5 h-5 text-primary" />,
                title: "Demonstrates Core AI Logic",
                text: "This feature perfectly showcases the core of the project: an AI agent using contextual data to provide intelligent, user-specific answers."
            }
        ]
    },
    {
        icon: <Server className="w-8 h-8 text-primary" />,
        title: "3. The Vision: Why We're Different Page",
        description: "Finally, briefly visit the 'Why We're Different' page to tie everything together.",
        points: [
            {
                icon: <LineChart className="w-5 h-5 text-primary" />,
                title: "Data Flow & Architecture",
                text: "Point to the diagrams we created. Explain that they show how the system is designed to be secure, scalable, and privacy-focused, with the Fi MCP server at its core."
            },
            {
                icon: <ShieldCheck className="w-5 h-5 text-emerald-500" />,
                title: "Reinforce the Core Message",
                text: "End the demo by reinforcing the main point: this isn't just a chatbot, it's a true financial agent that uses a robust architecture to provide hyper-personalized advice."
            }
        ]
    }
];

export default function DemoPage() {
    return (
        <div className="flex flex-col flex-1 p-4 md:p-8">
            <div className="mb-8 text-center">
                <h1 className="text-3xl font-bold tracking-tight md:text-4xl flex items-center justify-center gap-3">
                    <PlayCircle className="w-10 h-10 text-primary" />
                    <span>Live Demo Walkthrough</span>
                </h1>
                <p className="mt-2 text-lg text-muted-foreground">
                    Follow this script to deliver a winning presentation.
                </p>
            </div>

            <div className="max-w-4xl mx-auto space-y-8">
                {demoSteps.map((step, index) => (
                    <Card key={index} className="shadow-lg">
                        <CardHeader className="flex-row items-start gap-4">
                            <div className="flex items-center justify-center flex-shrink-0 w-16 h-16 rounded-lg bg-primary/10">
                                {step.icon}
                            </div>
                            <div>
                                <CardTitle className="text-2xl">{step.title}</CardTitle>
                                <CardDescription className="mt-1">{step.description}</CardDescription>
                            </div>
                        </CardHeader>
                        <CardContent className="space-y-4 pl-[88px] pt-0">
                            {step.points.map((point, pIndex) => (
                                <div key={pIndex} className="flex items-start gap-4">
                                    <div className="flex items-center justify-center w-8 h-8 mt-1 rounded-full bg-primary/10 shrink-0">
                                        {point.icon}
                                    </div>
                                    <div>
                                        <h4 className="font-semibold text-foreground">{point.title}</h4>
                                        <p className="text-sm text-muted-foreground">{point.text}</p>
                                    </div>
                                </div>
                            ))}
                             {step.title.includes("Vision") && (
                                <div className="pt-2">
                                     <Link href="/icons" className="text-primary hover:underline font-medium">
                                        Go to "Why We're Different" Page →
                                    </Link>
                                </div>
                            )}
                        </CardContent>
                    </Card>
                ))}
            </div>
             <div className="mt-12 text-center">
                <Card className="max-w-4xl mx-auto bg-emerald-500/10 border-emerald-500/50">
                    <CardHeader>
                        <CardTitle className="text-2xl text-emerald-700">Good Luck!</CardTitle>
                        <CardDescription className="text-emerald-600">
                            You've built an amazing project. Present it with confidence!
                        </CardDescription>
                    </CardHeader>
                </Card>
            </div>
        </div>
    );
}
