import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { FinancialData } from '@/lib/mcp-data';
import { PageHeader } from './page-header';
import { KpiCard } from './kpi-card';
import {
  Landmark,
  Wallet,
  BadgePercent,
  Receipt,
} from 'lucide-react';
import { FinancialSummary } from './financial-summary';
import { NetWorthChart } from './net-worth-chart';
import { AssetLiabilityChart } from './asset-liability-chart';
import { InvestmentPerformanceChart } from './investment-performance-chart';

type DashboardProps = {
  financialData: FinancialData;
};

export function Dashboard({ financialData }: DashboardProps) {
  return (
    <div className="flex flex-1 flex-col gap-6 p-4 md:gap-8 md:p-8 lg:p-10">
      <PageHeader userName={financialData.user.name} />
      <div className="grid gap-4 md:grid-cols-2 md:gap-8 lg:grid-cols-4">
        <KpiCard
          title="Total Assets"
          value={financialData.summary.assets}
          icon={<Landmark className="h-5 w-5" />}
        />
        <KpiCard
          title="Total Liabilities"
          value={financialData.summary.liabilities}
          icon={<Receipt className="h-5 w-5" />}
          isNegative
        />
        <KpiCard
          title="Net Worth"
          value={financialData.summary.netWorth}
          icon={<Wallet className="h-5 w-5" />}
          trend={financialData.netWorthHistory.slice(-2)}
          trendKey="value"
        />
        <KpiCard
          title="Credit Score"
          value={financialData.summary.creditScore}
          icon={<BadgePercent className="h-5 w-5" />}
          trend={financialData.creditScoreHistory.slice(-2)}
          trendKey="score"
        />
      </div>
      <div className="grid gap-4 md:gap-8 lg:grid-cols-2 xl:grid-cols-3">
        <Card className="xl:col-span-2 shadow-xl ring-8 ring-white dark:ring-black/20">
          <CardHeader>
            <CardTitle>Net Worth Over Time</CardTitle>
            <CardDescription>
              A historical view of your financial growth.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <NetWorthChart data={financialData.netWorthHistory} />
          </CardContent>
        </Card>
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle>Asset vs. Liability</CardTitle>
            <CardDescription>A breakdown of your financial standing.</CardDescription>
          </CardHeader>
          <CardContent>
            <AssetLiabilityChart data={financialData.summary} />
          </CardContent>
        </Card>
      </div>
      <div className="grid gap-4 md:gap-8 lg:grid-cols-2 xl:grid-cols-3">
        <Card className="shadow-lg xl:col-span-2">
          <CardHeader>
            <CardTitle>Investment Performance</CardTitle>
            <CardDescription>Annual performance of your investments.</CardDescription>
          </CardHeader>
          <CardContent className="pl-2">
            <InvestmentPerformanceChart data={financialData.assets.investments} />
          </CardContent>
        </Card>
        <Card className="shadow-lg xl:col-span-1">
          <CardHeader>
            <CardTitle>AI Financial Summary</CardTitle>
            <CardDescription>
              A personalized summary generated by Gemini.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <FinancialSummary financialData={financialData} />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
